#include<stdio.h>//khai bao thu vien stdio

int main(){//khoi tao ham main
	int a = 125, b = 12345;// khai bao bien a, b kieu int
	long ax = 1234567890;//khai bao bien kieu long
	short s = 4043;//khai bao bien kieu short
	float x = 2.13459;//khai bao bien x kieu float
	double dx = 1.41153552;//khai bao bien dx kieu double
	char c = 'W';// khai bao bien c kieu char 
	unsigned long ux = 124354;//khai bao bien ux kieu unsigned
	
	printf("a + c =  %d\n", a + c);//in ra............................
    printf("x + c = %f\n", x + c);//in ra............................
    printf("dx + x = %f\n", dx + x);//in ra............................
    printf("((int) dx) + ax =  %ld\n", ((int) dx) + ax);//in ra............................
    printf("a + x = %f\n", a + x);//in ra............................
    printf("s + b =  %d\n", s + b);//in ra............................
    printf("ax + b = %ld\n", ax + b);//in ra............................
    printf("s + c =  %hd\n", s + c);//in ra............................
    printf("ax + c = %ld\n", ax + c);//in ra............................
    printf("ax + ux = %lu\n", ax + ux);//in ra............................

    return 0;//tra ve ham main
}
